server:
  port: 8099
  servlet:
    context-path: /mcs-fuetes-indicadores-sm/api

spring:
  servlet: # <--- Configuración correcta para Spring Boot 3.x
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
  datasource:
    url: jdbc:sqlserver://sqlserver-1.cte66si2kd9h.eu-central-1.rds.amazonaws.com:1433;databaseName=BD_INDICADORES_SM;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;useBulkCopyForBatchInsert=true
    username: admin
    password: SzN2aW5AMTIzNDU2ZGVlKw==
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
springdoc:
  swagger-ui:
    path: /swagger-ui.html